# a better alternative than individual "docker build" and "docker run" commands is to use "docker compose"
# https://www.composerize.com/
# we also avoid passing explicit url with password inside an environment variable
# here we use Docker secrets approach to provide secret.txt
# this secret is then used to create a url dynamically
name: webapp-composed-prod

services:
  webapp-db:
    container_name: webapp-db-prod
    networks:
      webapp-net:
        aliases:
          - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    secrets:
      - postgres-password
    ports:
      - 5432:5432
    image: webapp-db:1.0prod
    build:
      context: ./webapp-db/

  webapp-backend:
    container_name: webapp-backend-prod
    networks:
      webapp-net:
        aliases:
          - api-node
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD_FILE=/run/secrets/postgres-password
    secrets:
      - postgres-password
    ports:
      - 3000:3000
    image: webapp-backend:1.0prod
    depends_on:
      - webapp-db
    build:
      context: ./api-node/
      target: prod

  webapp-frontend:
    container_name: webapp-frontend-prod
    networks:
      webapp-net:
        aliases:
          - client-react
    ports:
      - 8080:8080
    image: webapp-frontend:1.0prod
    build:
      context: ./client-react/
      target: prod

networks:
  webapp-net:
    name: webapp-net

secrets:
  postgres-password:
    file: ./webapp-db/secret.txt
