# this yml file allows hot reloading of the webapp-backend and webapp-frontend containers during development
# here we use simple volume/bind mount to provide secret.txt
name: webapp-composed-dev

services:
  webapp-db:
    container_name: webapp-db-dev
    networks:
      webapp-net:
        aliases:
          - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    ports:
      - 5432:5432
    volumes:
      - ./webapp-db/secret.txt:/run/secrets/postgres-password:ro
    image: webapp-db:1.0dev
    build:
      context: ./webapp-db/

  webapp-backend:
    container_name: webapp-backend-dev
    networks:
      webapp-net:
        aliases:
          - api-node
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD_FILE=/run/secrets/postgres-password
    ports:
      - 3000:3000
    image: webapp-backend:1.0dev
    depends_on:
      - webapp-db
    build:
      context: ./api-node/
      target: dev
    volumes:
      - ./webapp-db/secret.txt:/run/secrets/postgres-password:ro
        # shadow read-only and baked source code from the image with existing source code from the host
        # this allows reflecting changes made to the source code on the host without rebuilding the image
        # it is suppossed to be used only in development and not in production
      - type: bind
        source: ./api-node/src/
        target: /usr/src/app/src/
      # add anonymous volume overlay to the node_modules folder in the container to avoid overwriting it with the host's node_modules folder
      - type: volume
        target: /usr/src/app/node_modules

  webapp-frontend:
    container_name: webapp-frontend-dev
    networks:
      webapp-net:
        aliases:
          - client-react
    ports:
      - 5173:5173
    image: webapp-frontend:1.0dev
    build:
      context: ./client-react/
      target: dev
    volumes:
      # shadowing read-only and baked source code from the image with existing source code on the host
      - type: bind
        source: ./client-react/
        target: /usr/src/app/
      # anonymous volume overlay
      - type: volume
        target: /usr/src/app/node_modules
      - type: bind
        source: ./client-react/vite.config.js
        target: /usr/src/app/vite.config.js

networks:
  webapp-net:
    name: webapp-net
