# this file is built based on the docker-compose-prod.yml file and is used to deploy the webapp stack in production using docker stack deploy command
# both the "http://localhost:3000/" and the "http://localhost:3000/ping" endpoints should work and return the date and "pong", respectively
# the "http://localhost:8080/" should also work and return the welcome page
# as of now this file uses external secrets so make sure to create them before deploying the stack

services:
  webapp-db:
    networks:
      webapp-net:
        aliases:
          - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    secrets:
      - postgres-password
    ports:
      - 5432:5432
    image: 'tuilindo05/dockercourse-postgres:20261003-7e67f97'
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  webapp-backend:
    networks:
      webapp-net:
        aliases:
          - api-node
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD_FILE=/run/secrets/postgres-password
    secrets:
      # - external-swarm-secret
      # - non-external-secret
      - postgres-password
    ports:
      - 3000:3000
    image: 'tuilindo05/dockercourse-api-node:20261003-1114d47'
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        # start the new container before stopping the old one to avoid downtime and allow rolling updates
        order: start-first
    healthcheck:
      test: [ "CMD", "node", "/usr/src/app/healthcheck.js" ]
      # how often to run the health check command
      interval: 30s
      # how long to wait before considering the health check command to have failed
      timeout: 5s
      # how many consecutive failures are needed to consider the container as unhealthy
      retries: 3
      # how long to wait after starting the container before starting health checks
      start_period: 10s

  webapp-frontend:
    networks:
      webapp-net:
        aliases:
          - client-react
    ports:
      - 8080:8080
    image: 'tuilindo05/dockercourse-client-react:20261003-1114d47'
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        order: start-first
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 10s

networks:
  webapp-net:
    name: webapp-net

secrets:
  # external -> managed externally via "docker secret create" command
  # external-swarm-secret:
  #   external: true
  # non-external -> loaded from a local file
  # non-external-secret:
  #   file: ./webapp-db/secret.txt
  postgres-password:
    external: true
