# this yml file allows hot reloading of the webapp-api and webapp-client containers during development
# here we use simple volume/bind mount to provide secret.txt
name: webapp-composed-dev

services:
  webapp-db:
    container_name: webapp-db-dev
    networks:
      webapp-net:
        aliases:
          - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    ports:
      - 5432:5432
    volumes:
      - ./webapp-db/secret.txt:/run/secrets/postgres-password:ro
    image: webapp-db:1.0dev
    build:
      context: ./webapp-db/

  webapp-api:
    container_name: webapp-api-dev
    networks:
      webapp-net:
        aliases:
          - api-node
    env_file:
      - ./webapp-db/.env
    ports:
      - 3000:3000
    image: webapp-api:1.0dev
    depends_on:
      - webapp-db
    build:
      context: ./api-node/
      target: dev
    volumes:
        # shadow read-only and baked source code from the image with existing source code on the host
        # this allows reflecting changes made to the source code on the host without rebuilding the image
        # it is suppossed to be used only in development and not in production
      - type: bind
        source: ./api-node/src/
        target: /usr/src/app/src/
      - type: volume
        # add anonymous volume overlay to the node_modules folder in the container to avoid overwriting it with the host's node_modules folder
        target: /usr/src/app/node_modules

  webapp-client:
    container_name: webapp-client-dev
    networks:
      webapp-net:
        aliases:
          - client-react
    ports:
      - 5173:5173
    image: webapp-client:1.0dev
    build:
      context: ./client-react/
      target: dev
    volumes:
        # shadowing read-only and baked source code from the image with existing source code on the host
      - type: bind
        source: ./client-react/
        target: /usr/src/app/
      - type: volume
        # anonymous volume overlay
        target: /usr/src/app/node_modules
      - type: bind
        source: ./client-react/vite.config.js
        target: /usr/src/app/vite.config.js

networks:
  webapp-net:
    name: webapp-net
